server:
  port: 8000
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/greendb
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.format_sql]": true
  output:
    ansi:
      enabled: always

logging:
  level:
    "[org.hibernate.SQL]": DEBUG
    #root: DEBUG
